# Generated by Django 5.2.5 on 2025-09-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ship_registration_number',
            new_name='ship_reg_number',
        ),
    ]
