# Generated by Django 5.2.5 on 2025-09-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_ship_registration_number_user_ship_reg_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ship_reg_number',
            new_name='ship_number',
        ),
    ]