# Generated by Django 5.2.5 on 2025-09-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_ship_reg_number_user_ship_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ship_owner', 'Ship Owner'), ('captain', 'Captain'), ('fisherman', 'Fisherman'), ('processor', 'Processor'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('consumer', 'Consumer')], max_length=20),
        ),
    ]
