# Generated by Django 5.2.5 on 2025-09-02 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Perusahaan')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='NPWP')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kontak Person')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ship_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Pemilik Kapal',
                'verbose_name_plural': 'Profil Pemilik Kapal',
            },
        ),
        migrations.CreateModel(
            name='CaptainProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Lisensi')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='Tahun Pengalaman')),
                ('vessel_type_experience', models.TextField(blank=True, null=True, verbose_name='Pengalaman Jenis Kapal')),
                ('certification', models.TextField(blank=True, null=True, verbose_name='Sertifikasi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True, verbose_name='Kontak Darurat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captain_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Nahkoda',
                'verbose_name_plural': 'Profil Nahkoda',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='ID Pegawai')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departemen')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jabatan')),
                ('institution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institusi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Admin',
                'verbose_name_plural': 'Profil Admin',
            },
        ),
    ]