# Generated by Django 5.2.5 on 2025-09-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_user_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ship_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
