# Generated by Django 5.2.5 on 2025-09-02 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Ikan')),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Ilmiah')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Ikan',
                'verbose_name_plural': 'Jenis Ikan',
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Ikan')),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Ilmiah')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_fish', to='fishs.fishspecies', verbose_name='Jenis Ikan')),
            ],
            options={
                'verbose_name': 'Ikan',
                'verbose_name_plural': 'Ikan',
            },
        ),
    ]
