# Generated by Django 5.2.5 on 2025-09-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingarea',
            name='coordinates',
            field=models.TextField(blank=True, null=True, verbose_name='Koordinat'),
        ),
    ]
